from enum import IntEnum


class ErrorCode(IntEnum):
    EMAIL_ALREADY_REGISTERED = 1
    HOST_NAME_ALREADY_REGISTERED = 2
    GUEST_NAME_ALREADY_REGISTERED = 3
    EMAIL_NOT_EXIST = 4
    HOST_NAME_NOT_EXIST = 5
    PASSWORD_INCORRECT = 6
    REFRESH_TOKEN_INVALID = 7
