from enum import IntEnum


class ErrorCode(IntEnum):
    HOST_NAME_OR_EMAIL_ALREADY_REGISTERED = 1
    GUEST_NAME_ALREADY_REGISTERED = 2
    HOST_NAME_NOT_EXIST = 3
    GUEST_NAME_NOT_EXIST = 4
    PASSWORD_INCORRECT = 5
    REFRESH_TOKEN_INVALID = 6
    ACCOUNT_DISABLED = 7
