POINT_OUTLIER_THRESHOLD = 0.1
POINT_OUTLIER_SIGMOID_THRESHOLD = 0.3
POINT_OUTLIER_SIGMOID_COEFFICIENT = 10
SUBSEQUENCE_OUTLIER_THRESHOLD = 0.5
TIME_WINDOW_SIZE = 1
MAX_TIME_WINDOW_GAP = 1
AUTO_REG_LAGS = 32
