import os

from dotenv import load_dotenv

load_dotenv()

_DB_SHARD_COUNT = os.getenv("DB_SHARD_COUNT")
assert _DB_SHARD_COUNT is not None
DB_SHARD_COUNT = int(_DB_SHARD_COUNT)
AWS_RDS_CLUSTER_INSTANCE_URL = os.getenv("AWS_RDS_CLUSTER_INSTANCE_URL")
_AWS_RDS_CLUSTER_INSTANCE_PORT = os.getenv("AWS_RDS_CLUSTER_INSTANCE_PORT")
AWS_RDS_CLUSTER_INSTANCE_PORT = (
    int(_AWS_RDS_CLUSTER_INSTANCE_PORT)
    if _AWS_RDS_CLUSTER_INSTANCE_PORT is not None
    else None
)
AWS_RDS_CLUSTER_MASTER_USERNAME = os.getenv("AWS_RDS_CLUSTER_MASTER_USERNAME")
AURORA_COMMON_DBNAME = os.getenv("AURORA_COMMON_DBNAME")
AURORA_SEQUENCE_DBNAME = os.getenv("AURORA_SEQUENCE_DBNAME")
AURORA_SHARD_DBNAME_PREFIX = os.getenv("AURORA_SHARD_DBNAME_PREFIX")
