"""v1.0.4

Revision ID: 0a464d2315d1
Revises: a3a32fc8cd0b
Create Date: 2025-04-15 01:17:32.884328

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a464d2315d1"
down_revision: Union[str, None] = "a3a32fc8cd0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()


def upgrade_common() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_common() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_sequence() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_sequence() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_shard0() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_attendance_forecast",
        sa.Column("event_id", sa.BINARY(length=16), nullable=False, comment="Event ID"),
        sa.Column(
            "start",
            mysql.DATETIME(timezone=True),
            nullable=False,
            comment="Event Start Time",
        ),
        sa.Column(
            "forecasted_attended_at",
            mysql.DATETIME(timezone=True),
            nullable=False,
            comment="Forecasted Attendance Time",
        ),
        sa.Column(
            "forecasted_duration",
            mysql.BIGINT(unsigned=True),
            nullable=False,
            comment="Forecasted Duration in Seconds",
        ),
        sa.Column("id", sa.BINARY(length=16), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_attendance_forecast")),
        sa.UniqueConstraint(
            "user_id",
            "event_id",
            "start",
            name=op.f("uq_event_attendance_forecast_user_id"),
        ),
        info={"shard_ids": ("shard0", "shard1")},
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###


def downgrade_shard0() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_attendance_forecast")
    # ### end Alembic commands ###


def upgrade_shard1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_attendance_forecast",
        sa.Column("event_id", sa.BINARY(length=16), nullable=False, comment="Event ID"),
        sa.Column(
            "start",
            mysql.DATETIME(timezone=True),
            nullable=False,
            comment="Event Start Time",
        ),
        sa.Column(
            "forecasted_attended_at",
            mysql.DATETIME(timezone=True),
            nullable=False,
            comment="Forecasted Attendance Time",
        ),
        sa.Column(
            "forecasted_duration",
            mysql.BIGINT(unsigned=True),
            nullable=False,
            comment="Forecasted Duration in Seconds",
        ),
        sa.Column("id", sa.BINARY(length=16), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            mysql.DATETIME(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("user_id", mysql.BIGINT(unsigned=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_attendance_forecast")),
        sa.UniqueConstraint(
            "user_id",
            "event_id",
            "start",
            name=op.f("uq_event_attendance_forecast_user_id"),
        ),
        info={"shard_ids": ("shard0", "shard1")},
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###


def downgrade_shard1() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_attendance_forecast")
    # ### end Alembic commands ###
